# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kategoriview.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(486, 503)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 161, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelID = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelID.setObjectName("labelID")
        self.verticalLayout_2.addWidget(self.labelID)
        self.labelNama = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelNama.setObjectName("labelNama")
        self.verticalLayout_2.addWidget(self.labelNama)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(220, 30, 241, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEditID = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditID.setObjectName("lineEditID")
        self.verticalLayout_3.addWidget(self.lineEditID)
        self.lineEditNama = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditNama.setObjectName("lineEditNama")
        self.verticalLayout_3.addWidget(self.lineEditNama)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(29, 160, 431, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonInsert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        self.horizontalLayout.addWidget(self.pushButtonInsert)
        self.labelresult = QtWidgets.QLabel(Form)
        self.labelresult.setGeometry(QtCore.QRect(30, 210, 431, 31))
        self.labelresult.setObjectName("labelresult")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 250, 431, 201))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 460, 431, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonLoad = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout_2.addWidget(self.pushButtonLoad)
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonLoad.setFont(font)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout_2.addWidget(self.pushButtonLoad)
        self.pushButtonInsert.clicked.connect(self.insertkategori)
        self.pushButtonLoad.clicked.connect(self.loadkategori)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
    def insertkategori(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_penjualan"
            )
            cursor = mydb.cursor()
            idkat = self.lineEditID.text()
            namekat = self.lineEditNama.text()

            sql = "INSERT INTO kategori (id,name) VALUES (%s,%s)"
            val = (idkat,namekat)
            cursor.execute(sql,val)
            mydb.commit()
            self.labelresult.setText("Data Kategori Berhasil Disimpan")
            self.lineEditID.setText("")
            self.labelNama.setText("")
        except mc.Error as e:
            self.labelresult.setText("Data Kategori Gagal Disimpan")

    def loadkategori(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_penjualan"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM kategori ORDER BY ID ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,column_number, QTableWidgetItem(str(data)))
            self.labelresult.setText("Data Kategori Berhasil Ditampilkan")
        except mc.Error as err:
            self.labelresult.setText("Data Kategori Gagal DiLoad")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelID.setText(_translate("Form", "ID Kategori"))
        self.labelNama.setText(_translate("Form", "Nama Kategori"))
        self.pushButtonInsert.setText(_translate("Form", "INSERT DATA"))
        self.labelresult.setText(_translate("Form", "TextLabel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nama Kategori"))
        self.pushButtonLoad.setText(_translate("Form", "LOAD DATA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
