# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kategori.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class Ui_Kagetori(object):
    def setupUi(self, Kagetori):
        Kagetori.setObjectName("Kagetori")
        Kagetori.resize(405, 245)
        self.labelresult = QtWidgets.QLabel(Kagetori)
        self.labelresult.setGeometry(QtCore.QRect(20, 200, 361, 31))
        self.labelresult.setObjectName("labelresult")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Kagetori)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 121, 81))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelid = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelid.setObjectName("labelid")
        self.verticalLayout.addWidget(self.labelid)
        self.labelkategori = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelkategori.setObjectName("labelkategori")
        self.verticalLayout.addWidget(self.labelkategori)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Kagetori)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(170, 20, 211, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditID = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEditID.setObjectName("lineEditID")
        self.verticalLayout_2.addWidget(self.lineEditID)
        self.lineEditNama = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEditNama.setObjectName("lineEditNama")
        self.verticalLayout_2.addWidget(self.lineEditNama)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Kagetori)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 150, 361, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonInsert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        self.horizontalLayout.addWidget(self.pushButtonInsert)
        
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelresult.setFont(font)
        self.labelresult.setObjectName("labelResult")

        self.pushButtonInsert.clicked.connect(self.insertkategori)

        self.retranslateUi(Kagetori)
        QtCore.QMetaObject.connectSlotsByName(Kagetori)
        
    def insertkategori(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_penjualan"
            )
            cursor = mydb.cursor()
            idkat = self.lineEditID.text()
            namekat = self.lineEditNama.text()
            
            sql = "INSERT INTO kategori (id,name) VALUES (%s,%s)"
            val = (idkat,namekat)
            cursor.execute(sql,val)
            mydb.commit()
            self.labelresult.setText("Data Kategori Berhasil Disimpan")
            self.lineEditID.setText("")
            self.lineEditNama.setText("")
        except mc.Error as e:
            self.labelresult.setText("Data Kategori Gagal Disimpan")

    def retranslateUi(self, Kagetori):
        _translate = QtCore.QCoreApplication.translate
        Kagetori.setWindowTitle(_translate("Kagetori", "Form"))
        self.labelresult.setText(_translate("Kagetori", "TextLabel"))
        self.labelid.setText(_translate("Kagetori", "ID Kategori"))
        self.labelkategori.setText(_translate("Kagetori", "Nama Kategori"))
        self.pushButtonInsert.setText(_translate("Kagetori", "INSERT DATA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Kagetori = QtWidgets.QWidget()
    ui = Ui_Kagetori()
    ui.setupUi(Kagetori)
    Kagetori.show()
    sys.exit(app.exec_())
