# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ai.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import mysql.connector as mc
from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QTableWidgetItem

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(825, 971)
        self.verticalLayoutWidget = QtWidgets.QWidget(Frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 141, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(169, 19, 611, 351))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.id = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.id.setObjectName("id")
        self.verticalLayout_3.addWidget(self.id)
        self.barkode = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.barkode.setObjectName("barkode")
        self.verticalLayout_3.addWidget(self.barkode)
        self.nama = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.nama.setObjectName("nama")
        self.verticalLayout_3.addWidget(self.nama)
        self.kategori = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.kategori.setObjectName("kategori")
        self.verticalLayout_3.addWidget(self.kategori)
        self.qty = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.qty.setObjectName("qty")
        self.verticalLayout_3.addWidget(self.qty)
        self.harga = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.harga.setObjectName("harga")
        self.verticalLayout_3.addWidget(self.harga)
        self.labelResult = QtWidgets.QLabel(Frame)
        self.labelResult.setGeometry(QtCore.QRect(20, 470, 761, 41))
        self.labelResult.setObjectName("labelResult")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 520, 761, 191))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.table = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.table.setObjectName("table")
        self.table.setColumnCount(6)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        self.verticalLayout_4.addWidget(self.table)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 720, 761, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditSearching = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditSearching.setObjectName("lineEditSearching")
        self.horizontalLayout_2.addWidget(self.lineEditSearching)
        self.pushButtonSearching = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonSearching.setObjectName("pushButtonSearching")
        self.horizontalLayout_2.addWidget(self.pushButtonSearching)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 380, 761, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.insert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.insert.setObjectName("insert")
        self.horizontalLayout.addWidget(self.insert)
        self.update = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.update.setObjectName("update")
        self.horizontalLayout.addWidget(self.update)
        self.btndelete = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btndelete.setObjectName("btndelete")
        self.horizontalLayout.addWidget(self.btndelete)
        self.load = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.load.setObjectName("load")
        self.horizontalLayout.addWidget(self.load)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(60, 810, 491, 51))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_5.addWidget(self.listWidget)
        self.insert.clicked.connect(self.insertproduct)
        self.update.clicked.connect(self.updateproduct)
        self.btndelete.clicked.connect(self.deleteproduct)
        self.load.clicked.connect(self.loadproduct)
        self.pushButtonSearching.clicked.connect(self.searchingproduct)
        self.table.cellClicked.connect(self.handleCellClick)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def handleCellClick(self, row, column):
        try:
            idprod = self.table.item(row, 0).text()
            bar = self.table.item(row, 1).text()
            nameprod = self.table.item(row, 2).text()
            kat = self.table.item(row, 3).text()
            qt = self.table.item(row, 4).text()
            hrg = self.table.item(row, 5).text()
            self.id.setText(idprod)
            self.barkode.setText(bar)
            self.nama.setText(nameprod)
            self.kategori.setText(kat)
            self.qty.setText(qt)
            self.harga.setText(hrg)
            self.labelResult.setText("Data Product Ditampilkan di Input")
        except Exception as e:
            self.labelResult.setText("Data Product Gagal Ditampilkan Di Input")


    def insertproduct(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "db_penjualan"
            )
            cursor = mydb.cursor()
            idprod = self.id.text()
            bar = self.barkode.text()
            nameprod = self.nama.text()
            kat = self.kategori.text()
            qt = self.qty.text()
            hrg = self.harga.text()
            sql = "INSERT INTO product (id, barkode, name, kategori, qty, harga) VALUES (%s,%s,%s,%s,%s,%s)"
            val = (idprod, bar, nameprod, kat, qt, hrg)
            cursor.execute(sql,val)
            mydb.commit()
            self.labelResult.setText("Data Product Berhasil Disimpan")
            self.id.setText("")
            self.barkode.setText("")
            self.nama.setText("")
            self.kategori.setText("")
            self.qty.setText("")
            self.harga.setText("")
        except mc.Error as e:
            self.labelResult.setText("Data Product Gagal Disimpan")

    def updateproduct(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "db_penjualan"
            )
            cursor = mydb.cursor()
            idprod = self.id.text()
            bar = self.barkode.text()
            nameprod = self.nama.text()
            kat = self.kategori.text()
            qt = self.qty.text()
            hrg = self.harga.text()
            sql = "UPDATE product SET barkode = %s, name = %s, kategori = %s, qty = %s, harga = %s WHERE id = %s"
            val = (bar, nameprod, kat, qt, hrg, idprod)
            cursor.execute(sql,val)
            mydb.commit()
            self.labelResult.setText("Data Product Berhasil Diubah")
            self.id.setText("")
            self.barkode.setText("")
            self.nama.setText("")
            self.kategori.setText("")
            self.qty.setText("")
            self.harga.setText("")
        except mc.Error as e:
            self.labelResult.setText("Data Product Gagal Diubah")

    def deleteproduct(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "db_penjualan"
            )
            cursor = mydb.cursor()
            idprod = self.id.text()
            bar = self.barkode.text()
            nameprod = self.nama.text()
            qt = self.qty.text()
            kat = self.kategori.text()
            hrg = self.harga.text()
            sql = "DELETE FROM product WHERE id LIKE %s AND barkode LIKE %s AND name LIKE %s AND kategori LIKE %s AND qty LIKE %s AND harga LIKE %s"
            val = (idprod, bar, nameprod, kat, qt, hrg)
            cursor.execute(sql, val)
            mydb.commit()
            self.labelResult.setText("Data Product Berhasil Dihapus")
            self.id.setText("")
            self.barkode.setText("")
            self.nama.setText("")
            self.kategori.setText("")
            self.qty.setText("")
            self.harga.setText("")
        except mc.Error as e:
            self.labelResult.setText("Data Product Gagal Dihapus")

    def loadproduct(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "db_penjualan"
            )
            cursor = mydb.cursor()
        
            cursor.execute("SELECT * FROM product ORDER BY ID ASC")
            result = cursor.fetchall()
            self.table.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.table.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.table.setItem(row_number,column_number, QTableWidgetItem(str(data)))
                    self.labelResult.setText("Data Produt Berhasil Ditampilkan")
        except mc.Error as e:
            self.labelResult.setText("Data Product Gagal Di Load")

    def searchingproduct(self):
        try:
            keyword = self.lineEditSearching.text()
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "db_penjualan"
            )
            cursor = mydb.cursor()
            sql = "SELECT * FROM product WHERE id LIKE %s OR barkode LIKE %s OR name LIKE %s OR kategori LIKE %s OR qty LIKE %s OR harga LIKE %s"
            val = ("%{}%".format(keyword), "%{}%".format(keyword), "%{}%".format(keyword), "%{}%".format(keyword), "%{}%".format(keyword), "%{}%".format(keyword))
            cursor.execute(sql, val)
            result = cursor.fetchall()
            if not result:
                self.labelResult.setText("Data Kategori Yang Dicari Tidak Ada")
                self.table.setRowCount(0)
                return
            self.table.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.table.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.table.setItem(row_number, column_number, QTableWidgetItem(str(data)))
                self.labelResult.setText
        except mc.Error as e:
            self.labelResult.setText("Terjadi Kesalahan Saat Mencari Data")

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "ID"))
        self.label_2.setText(_translate("Frame", "Barkode"))
        self.label_3.setText(_translate("Frame", "Nama"))
        self.label_4.setText(_translate("Frame", "Kategori"))
        self.label_5.setText(_translate("Frame", "Qty"))
        self.label_6.setText(_translate("Frame", "Harga"))
        self.labelResult.setText(_translate("Frame", "ket"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Frame", "Id"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Frame", "Barkode"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Frame", "Nama"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("Frame", "Qty"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("Frame", "Kategori"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("Frame", "Harga"))
        self.pushButtonSearching.setText(_translate("Frame", "Searching"))
        self.insert.setText(_translate("Frame", "INSERT"))
        self.update.setText(_translate("Frame", "UPDATE"))
        self.btndelete.setText(_translate("Frame", "DELETE"))
        self.load.setText(_translate("Frame", "LOAD DATA"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Frame", "M. Yusril Maulana - 2210010454 5M"))
        self.listWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
