# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crudfilter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import mysql.connector as mc
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(937, 688)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(89, 50, 161, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelNpm = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelNpm.setObjectName("labelNpm")
        self.verticalLayout.addWidget(self.labelNpm)
        self.labelName = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelName.setObjectName("labelName")
        self.verticalLayout.addWidget(self.labelName)
        self.labelKls = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelKls.setObjectName("labelKls")
        self.verticalLayout.addWidget(self.labelKls)
        self.labelJurusan = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelJurusan.setObjectName("labelJurusan")
        self.verticalLayout.addWidget(self.labelJurusan)
        self.labelTglLahir = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelTglLahir.setObjectName("labelTglLahir")
        self.verticalLayout.addWidget(self.labelTglLahir)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(90, 560, 761, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditSearching = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditSearching.setObjectName("lineEditSearching")
        self.horizontalLayout_2.addWidget(self.lineEditSearching)
        self.pushButtonSearching = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonSearching.setObjectName("pushButtonSearching")
        self.horizontalLayout_2.addWidget(self.pushButtonSearching)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 260, 761, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonInsert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        self.horizontalLayout.addWidget(self.pushButtonInsert)
        self.pushButtonUpdate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.horizontalLayout.addWidget(self.pushButtonUpdate)
        self.pushButtonDelete = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout.addWidget(self.pushButtonDelete)
        self.pushButtonLoad = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout.addWidget(self.pushButtonLoad)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(250, 50, 601, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditNpm = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditNpm.setObjectName("lineEditNpm")
        self.verticalLayout_2.addWidget(self.lineEditNpm)
        self.lineEditName = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditName.setObjectName("lineEditName")
        self.verticalLayout_2.addWidget(self.lineEditName)
        self.lineEditKls = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditKls.setObjectName("lineEditKls")
        self.verticalLayout_2.addWidget(self.lineEditKls)
        self.lineEditJurusan = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditJurusan.setObjectName("lineEditJurusan")
        self.verticalLayout_2.addWidget(self.lineEditJurusan)
        self.lineEditTgl = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditTgl.setObjectName("lineEditTgl")
        self.verticalLayout_2.addWidget(self.lineEditTgl)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(90, 360, 761, 191))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.labelResult = QtWidgets.QLabel(Form)
        self.labelResult.setGeometry(QtCore.QRect(90, 310, 761, 41))
        self.labelResult.setObjectName("labelResult")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_5.addWidget(self.listWidget)


        self.pushButtonInsert.clicked.connect(self.insertmahasiswa)
        self.pushButtonUpdate.clicked.connect(self.updatemahasiswa)
        self.pushButtonDelete.clicked.connect(self.deletemahasiswa)
        self.pushButtonLoad.clicked.connect(self.loadmahasiswa)
        self.pushButtonSearching.clicked.connect(self.searchingmahasiswa)
        self.tableWidget.cellClicked.connect(self.handleCellClick)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def handleCellClick(self, row, column):
        try:
            npm= self.tableWidget.item(row, 0).text()
            name = self.tableWidget.item(row, 1).text()
            kelas= self.tableWidget.item(row, 2).text()
            jurusan = self.tableWidget.item(row, 3).text()
            tgl_lahir= self.tableWidget.item(row, 4).text()
            self.lineEditNpm.setText(npm)
            self.lineEditName.setText(name)
            self.lineEditKls.setText(kelas)
            self.lineEditJurusan.setText(jurusan)
            self.lineEditTgl.setText(tgl_lahir)
            self.labelResult.setText("Data Mahasiswa Ditampilkan di Input")
        except Exception as e:
            self.labelResult.setText("Data Mahasiswa Gagal Ditampilkan di Input")

    def insertmahasiswa(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_kampus"
            )
            cursor = mydb.cursor()
            npm= self.lineEditNpm.text()
            nama = self.lineEditName.text()
            kelas= self.lineEditKls.text()
            jurusan = self.lineEditJurusan.text()
            tgl_lahir= self.lineEditTgl.text()
            sql = "INSERT INTO mahasiswa (npm,nama,kelas,jurusan,tgl_lahir) VALUES (%s,%s,%s,%s,%s)"
            val = (npm,nama,kelas,jurusan,tgl_lahir)
            cursor.execute(sql,val)
            mydb.commit()
            self.labelResult.setText("Data Mahasiswa Berhasil Disimpan")
            self.lineEditNpm.setText("")
            self.lineEditName.setText("")
            self.lineEditKls.setText("")
            self.lineEditJurusan.setText("")
            self.lineEditTgl.setText("")
        except mc.Error as e:
            self.labelResult.setText("Data Mahasiswa Gagal Disimpan")



    def updatemahasiswa(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_kampus"
            )
            cursor = mydb.cursor()
            npm= self.lineEditNpm.text()
            name = self.lineEditName.text()
            kelas= self.lineEditKls.text()
            jurusan = self.lineEditJurusan.text()
            tgl_lahir= self.lineEditTgl.text()
            sql = "UPDATE mahasiswa SET nama = %s, kelas = %s, jurusan = %s, tgl_lahir = %s WHERE npm=%s"
            val = (name,kelas,jurusan,tgl_lahir,npm)
            cursor.execute(sql,val)
            mydb.commit()
            self.labelResult.setText("Data Mahasiswa Berhasil Diubah")
            self.lineEditNpm.setText("")
            self.lineEditName.setText("")
        except mc.Error as e:
            self.labelResult.setText("Data Mahasiswa Gagal Diubah")



    def deletemahasiswa(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_kampus"
            )
            cursor = mydb.cursor()
            npm = self.lineEditNpm.text()
            name = self.lineEditName.text()
            kelas= self.lineEditKls.text()
            jurusan = self.lineEditJurusan.text()
            tgl_lahir= self.lineEditTgl.text()
            sql = "DELETE FROM mahasiswa WHERE npm =%s AND nama =%s AND kelas =%s AND jurusan =%s AND tgl_lahir =%s"
            val = (npm, name, kelas, jurusan, tgl_lahir)
            cursor.execute(sql, val)
            mydb.commit()
            self.labelResult.setText("Data Mahasiswa Berhasil Dihapus")
            self.lineEditNpm.setText("")
        except mc.Error as e:
            self.labelResult.setText("Data Mahasiswa Gagal Dihapus")


    def loadmahasiswa(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_kampus"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM mahasiswa ORDER BY NPM ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,column_number, QTableWidgetItem(str(data)))
                    self.labelResult.setText("Data Mahasiswa Berhasil Ditampilkan")
        except mc.Error as e:
            self.labelResult.setText("Data Mahasiswa Gagal DiLoad")

    def searchingmahasiswa(self):
        try:
            keyword = self.lineEditSearching.text()
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_kampus"
            )
            cursor = mydb.cursor()
            sql = "SELECT * FROM mahasiswa WHERE npm LIKE %s OR nama LIKE %s OR kelas LIKE %s OR jurusan LIKE %s OR tgl_lahir LIKE %s"
            val = ("%{}%".format(keyword), "%{}%".format(keyword),  "%{}%".format(keyword),  "%{}%".format(keyword),  "%{}%".format(keyword))
            cursor.execute(sql, val)
            result = cursor.fetchall()
            if not result:
                self.labelResult.setText("Data mahasiswa Yang Dicari Tidak Ada")
                self.tableWidget.setRowCount(0)
                return
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
                self.labelResult.setText("Data mahasiswa Yang Dicari Ditampilkan")
        except mc.Error as e:
            self.labelResult.setText("Terjadi Kesalahan Saat Mencari Data")


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelNpm.setText(_translate("Form", "NPM"))
        self.labelName.setText(_translate("Form", "Nama "))
        self.labelKls.setText(_translate("Form", "Kelas"))
        self.labelJurusan.setText(_translate("Form", "Jurusan"))
        self.labelTglLahir.setText(_translate("Form", "Tanggal Lahir"))
        self.pushButtonSearching.setText(_translate("Form", "Searching"))
        self.pushButtonInsert.setText(_translate("Form", "INSERT"))
        self.pushButtonUpdate.setText(_translate("Form", "UPDATE"))
        self.pushButtonDelete.setText(_translate("Form", "DELETE"))
        self.pushButtonLoad.setText(_translate("Form", "LOAD DATA"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "NPM"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Kelas"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Jurusan"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tanggal Lahir"))
        self.labelResult.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
